### ISSUE TITLE
broken in Gajim 0.99.1

### ISSUE THREAD

**Issue by mightyBroccoli** [jplitza/gajim-emojione#2]
These emojis do not work anymore in Gajim 0.99.1. 

```
12.02.2018 11:30:38 (E) gajim.emoticons Emoticons theme not found
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gajim/emoticons.py", line 71, in load
    theme = loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/home/~/.local/share/gajim/emoticons/Gajim emojione/emoticons_theme.py'
```

**Comment by flobee** [comment]
Hi! Thx feedback and for giving me a hint at jabber :) 
Well, sry: debian stable release has "Gajim 0.16.8" :(
I will give feedback after upgrade... this may take some time! sry!
